name: Package 1 Workflow

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string

jobs:
  execute_package1_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: change directory
        run: cd packages/${{ inputs.package_name }}

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: install dependencies
        run: npm install

      - name: list
        run: ls
