name: Publish Workflow

on:
  workflow_call:
    inputs:
      package_names:
        required: true
        type: string

jobs:
  publish_workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package_name: ${{fromJson(inputs.package_names)}}

    name: Publishing ${{ matrix.package_name }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: install and publish
        run: |
          cd packages/${{ matrix.package_name }}
          npm install
