name: Package 1 Workflow

on:
  workflow_call:

jobs:
  execute_package1_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: change directory
        run: cd packages/package1

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: isntall dependencies
        run: npm install
