name: Package 1 Workflow

on:
  workflow_call:

jobs:
  execute_package1_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: List
        run: ls
